

/*
 *   Generated by  UI v2.00 
 *        February 21, 1995
 */


/* Module: ADA_4SYS.C ===================== */

#include <string.h>
#include <stdlib.h>

#include <tcxlcur.h>
#include <tcxlnls.h>
#include <tcxlwin.h>
#include <tcxlent.h>
#include <tcxlmnu.h>
#include <tcxlcod.h>
#include <tcxlinp.h>
#include <tcxlsel.h>
#include <tcxlstr.h>
#include <tcxlvid.h>
#include <tcxlhlp.h>

#define HLP_NONE 1


#ifndef __Struct_WDEF_
#define __Struct_WDEF_

       struct _WDEF
         {
         IntT BegC,BegR,EndC,EndR;   /* положение окна    */
         IntT MniC,MniR,MaxC,MaxR;   /* возможные размеры */
         BytT FrmT;                  /* тип бордюра       */
         AtrT FrmA;                  /* атрибуты бордюра  */
         AtrT Dat;                   /* атрибуты текста   */
         BytT Shadow;                /* тень              */
         AtrT Sat;                   /* цвет тени         */
         };
#endif

#ifdef __cplusplus
  extern "C" {
#endif
VOID CTYP MnuDsp(MbldP mnu);
KeyT CTYP EntSelect(NOARG);
GBL  IntT EntSelAct;
LCL  IntT EntResult;
#ifdef __cplusplus
   }
#endif
#include "pro_achh.h"

VOID CTYP _Init_SHOW(NOARG);
VOID CTYP _startup_EXEC(NOARG);
VOID CTYP _shutdown_EXEC(NOARG);
VOID CTYP _do_init_EXEC(NOARG);
VOID CTYP _sys_har_MENU(NOARG);
VOID CTYP _har_model_ENTRY(NOARG);
VOID CTYP _wid_et_s_MENU(NOARG);
VOID CTYP _wid_upr_MENU(NOARG);
VOID CTYP _razgruzka_EXEC(NOARG);
VOID CTYP _static_mn_MENU(NOARG);
VOID CTYP _wz_stat_EXEC(NOARG);
VOID CTYP _do_achh_EXEC(NOARG);
VOID CTYP _file_et_ENTRY(NOARG);
VOID CTYP _ifile_et_ENTRY(NOARG);
VOID CTYP _file_upr_ENTRY(NOARG);
VOID CTYP _ish_d_static_ENTRY(NOARG);
VOID CTYP _stat_msg_SHOW(NOARG);
VOID CTYP _tabl_stat_EXEC(NOARG);
VOID CTYP _grf_stat_EXEC(NOARG);
VOID CTYP _file_st_ENTRY(NOARG);
VOID CTYP _wybor_EXEC(NOARG);
VOID CTYP _write_et_EXEC(NOARG);
VOID CTYP _write_upr_EXEC(NOARG);
VOID CTYP _uw_EXEC(NOARG);
VOID CTYP _um_EXEC(NOARG);
VOID CTYP _do_stat_EXEC(NOARG);
VOID CTYP _write_st_EXEC(NOARG);
VOID CTYP _background_2STR(NOARG);
VOID CTYP _main_2STR(NOARG);
VOID CTYP _main_MSG(NOARG);
VOID CTYP _Init_2STR(NOARG);
VOID CTYP _sys_har_2STR(NOARG);
VOID CTYP _sys_har_MSG(NOARG);
VOID CTYP _har_model_2STR(NOARG);
VOID CTYP _har_model_OPEN(NOARG);
VOID CTYP _wid_et_s_2STR(NOARG);
VOID CTYP _wid_et_s_MSG(NOARG);
VOID CTYP _wid_upr_2STR(NOARG);
VOID CTYP _wid_upr_MSG(NOARG);
VOID CTYP _static_mn_2STR(NOARG);
VOID CTYP _static_mn_MSG(NOARG);
VOID CTYP _file_et_2STR(NOARG);
VOID CTYP _file_et_OPEN(NOARG);
VOID CTYP _ifile_et_2STR(NOARG);
VOID CTYP _ifile_et_OPEN(NOARG);
VOID CTYP _file_upr_2STR(NOARG);
VOID CTYP _file_upr_OPEN(NOARG);
VOID CTYP _ish_d_static_2STR(NOARG);
VOID CTYP _ish_d_static_OPEN(NOARG);
VOID CTYP _stat_msg_2STR(NOARG);
VOID CTYP _file_st_2STR(NOARG);
VOID CTYP _file_st_OPEN(NOARG);


LCL VOID CTYP _opt2_ACT(NOARG)
{
sys_har();
return;
}

LCL IbldT _main_Itm[]={
{"  (C)  ",'\0',ITM_NOR,0,0,  1,HLP_NONE,
   0,2,NULL,NULL,NULL,
   "",NULL},
{"Система",'\0',ITM_NOR,0,8,  3,HLP_NONE,
   0,4,NULL,_opt2_ACT,NULL,
   "",NULL},
{"Характеристики",'\0',ITM_NOR,0,16,  5,HLP_NONE,
   0,6,NULL,_sys_har_MENU,NULL,
   "",NULL},
{"Модель подстройки",'\0',ITM_NOR,0,31,  7,HLP_NONE,
   0,8,NULL,_har_model_ENTRY,NULL,
   "",NULL},
{"Эталонный сигнал",'\0',ITM_NOR,0,49,  9,HLP_NONE,
   0,10,NULL,_wid_et_s_MENU,NULL,
   "",NULL},
{"Управление",'\0',ITM_NOR,0,66,  11,HLP_NONE,
   0,12,NULL,_wid_upr_MENU,NULL,
   "",NULL},
};


LCL VOID CTYP _main_MSG(NOARG);
LCL MbldT _main_Mnu={
   _main_Itm,6,1,1,3,78,  MNU_OMN|MNU_SAV|MNU_DSP|MNU_NQS,BOX_SNG,
   _BLUE|INTENSE|LGREY,_BLUE|INTENSE|LGREY,_BLUE|INTENSE|LGREY,
   _BLUE|BLACK,_BLUE|BLACK,_CYAN|BLACK,
   0,_main_MSG,13, 10,0,0, 0xff,0xff,0xff};

LCL VOID CTYP _main_MSG(NOARG)
{

 CurHide();
  Wmessage("\020" " ",BRD_TOP,25,_BLUE|INTENSE|LGREY);
  Wmessage("Главное меню программы",BRD_TOP,27,_MAGENTA|INTENSE|BROWN);
  Wmessage(" \021" "",BRD_TOP,49,_BLUE|INTENSE|LGREY);
  {
  MnuDsp(&_main_Mnu);
  }
  return;
}
LCL VOID CTYP _Init_SHOW(NOARG)
{
  _razgruzka_EXEC();
 Wopen(8,19,21,65,BOX_DBL,
       _MAGENTA|INTENSE|LGREY,_MAGENTA|INTENSE|LGREY);
 Wshadow(_BLACK|DGREY);
 CurHide();
  Wprts(0,14,_MAGENTA|INTENSE|GREEN,"В Н И М А Н И Е !");
  Wprts(2,8,_MAGENTA|INTENSE|LGREY,"Осуществите");
  Wprts(2,20,_MAGENTA|INTENSE|LGREY,"разгрузку");
  Wprts(2,30,_MAGENTA|INTENSE|LGREY,"стенда");
  Wprts(4,4,_MAGENTA|INTENSE|LGREY,"по");
  Wprts(4,7,_MAGENTA|INTENSE|LGREY,"всем");
  Wprts(4,12,_MAGENTA|INTENSE|LGREY,"каналам");
  Wprts(4,20,_MAGENTA|INTENSE|LGREY,"со");
  Wprts(4,23,_MAGENTA|INTENSE|LGREY,"стойки");
  Wprts(4,30,_MAGENTA|INTENSE|LGREY,"управления,");
  Wprts(6,4,_MAGENTA|INTENSE|LGREY,"подключите");
  Wprts(6,15,_MAGENTA|INTENSE|LGREY,"сигнальные");
  Wprts(6,26,_MAGENTA|INTENSE|LGREY,"шины");
  Wprts(6,31,_MAGENTA|INTENSE|LGREY,"компьютера");
  Wprts(8,5,_MAGENTA|INTENSE|LGREY,"к");
  Wprts(8,7,_MAGENTA|INTENSE|LGREY,"прямым");
  Wprts(8,14,_MAGENTA|INTENSE|LGREY,"и");
  Wprts(8,16,_MAGENTA|INTENSE|LGREY,"обратным");
  Wprts(8,25,_MAGENTA|INTENSE|LGREY,"каналам");
  Wprts(8,33,_MAGENTA|INTENSE|LGREY,"системы");
  Wprts(10,13,_MAGENTA|INTENSE|LGREY,"управления");
  Wprts(10,24,_MAGENTA|INTENSE|LGREY,"стендом");
   {
 KbndP tcxl_old_kb,tcxl_kb=NULL;
 tcxl_old_kb=KbndChg(tcxl_kb);
 KbndChg(tcxl_old_kb);
   }
 MouPush(MOU_FULL);
 CurHide();
 KeyWait();
 CurShow();
 MouPop();
 Wclose();
 return;
}
LCL VOID CTYP _startup_EXEC(NOARG)
{
StartUp();  
  return;
}
LCL VOID CTYP _shutdown_EXEC(NOARG)
{
ShutDown(); 
  return;
}
LCL VOID CTYP _do_init_EXEC(NOARG)
{
_Init_SHOW();
  return;
}

LCL VOID CTYP _opt7_ACT(NOARG)
{
/**/
_static_mn_MENU();
return;
}

LCL VOID CTYP _opt10_ACT(NOARG)
{
/**/
_wz_stat_EXEC();
return;
}

LCL VOID CTYP _opt14_ACT(NOARG)
{
/**/
return;
}

LCL VOID CTYP _opt17_ACT(NOARG)
{
/**/
_do_achh_EXEC();
return;
}

LCL VOID CTYP _opt20_ACT(NOARG)
{
/**/
return;
}

LCL IbldT _sys_har_Itm[]={
{"    Статические характеристики     ",'1',ITM_NOR,1,2,  14,HLP_NONE,
   0,15,NULL,_opt7_ACT,NULL,
   "",NULL},
{"     Взаимодействие в статике      ",'2',ITM_NOR,2,2,  16,HLP_NONE,
   0,17,NULL,_opt10_ACT,NULL,
   "",NULL},
{"    Динамическ. характеристики     ",'4',ITM_NOR,4,2,  18,HLP_NONE,
   0,19,NULL,_opt14_ACT,NULL,
   "",NULL},
{"Амплитудно-частотные характеристики",'5',ITM_NOR,5,2,  20,HLP_NONE,
   0,21,NULL,_opt17_ACT,NULL,
   "",NULL},
{"     Взаимодействие в динамике     ",'6',ITM_NOR,6,2,  22,HLP_NONE,
   0,23,NULL,_opt20_ACT,NULL,
   "",NULL},
};


LCL VOID CTYP _sys_har_MSG(NOARG);
LCL MbldT _sys_har_Mnu={
   _sys_har_Itm,5,4,2,13,42,  MNU_OMN|MNU_SAV|MNU_DSP|MNU_NQS,BOX_SNG,
   _LGREY|BROWN,_BLUE|INTENSE|LGREY,_BLUE|INTENSE|LGREY,
   _BLUE|BLACK,_BLUE|BLACK,_CYAN|BLACK,
   0,_sys_har_MSG,24, 10,0,0, 0xff,0xff,0xff};

LCL VOID CTYP _sys_har_MSG(NOARG)
{

 CurHide();
  Wprts(0,1,_BLUE|INTENSE|BROWN,"┌───────────\020" " Статика \021" "─────────────┐");
  Wprts(1,1,_BLUE|INTENSE|BROWN,"│");
  Wprts(1,37,_BLUE|INTENSE|BROWN,"│");
  Wprts(2,1,_BLUE|INTENSE|BROWN,"│");
  Wprts(2,37,_BLUE|INTENSE|BROWN,"│");
  Wprts(3,1,_BLUE|INTENSE|BROWN,"├───────────\020" " Динамика \021" "────────────┤");
  Wprts(4,1,_BLUE|INTENSE|BROWN,"│");
  Wprts(4,37,_BLUE|INTENSE|BROWN,"│");
  Wprts(5,1,_BLUE|INTENSE|BROWN,"│");
  Wprts(5,37,_BLUE|INTENSE|BROWN,"│");
  Wprts(6,1,_BLUE|INTENSE|BROWN,"│");
  Wprts(6,37,_BLUE|INTENSE|BROWN,"│");
  Wprts(7,1,_BLUE|INTENSE|BROWN,"└───────────────────────────────────┘");
  {
  MnuDsp(&_sys_har_Mnu);
  }
  return;
}
LCL VOID CTYP _sys_har_MENU(NOARG)
{
 KbndP tcxl_old_kb,tcxl_kb=NULL;

 MbldTag(&_sys_har_Mnu)=IbldTag(&_sys_har_Itm[0]);
 tcxl_old_kb=KbndChg(tcxl_kb);

 MnuBuild(&_sys_har_Mnu);
 MnuGet();
 KbndChg(tcxl_old_kb);
}

LCL ChrT har_model_var2[16];
LCL ChrT har_model_var5[3];
LCL ChrT har_model_var6[3];
LCL ChrT har_model_var8[3];
LCL ChrT har_model_var9[3];
LCL FbldT _har_model_Fld[]={
 {"",0,0, har_model_var2,1,12,
  "***************",NULL,NULL,NULL,
  0,25,HLP_NONE,
  FLD_DIS|FLD_TRM,0,FLD_CHG},
 {"",0,0, har_model_var5,3,22,
  "99",NULL,NULL,NULL,
  0,26,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, har_model_var6,4,22,
  "99",NULL,NULL,NULL,
  0,27,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, har_model_var8,6,22,
  "99",NULL,NULL,NULL,
  0,28,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, har_model_var9,7,22,
  "99",NULL,NULL,NULL,
  0,29,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
};

LCL EbldT _har_model_Frm={
 _har_model_Fld,5,NULL,NULL,30,0,
 0,_CYAN|BLACK,_BLUE|INTENSE|GREEN,_BLACK|DGREY
};
LCL VOID CTYP _har_model_OPEN(NOARG)
{

 Wopen(4,28,16,57,BOX_SNG,
       _MAGENTA|INTENSE|GREEN,_CYAN|BLACK);
 CurHide();
  Wbprintc(BRD_LFT,9,_MAGENTA|INTENSE|GREEN,'├');
  Wbprintc(BRD_RGT,4,_MAGENTA|INTENSE|GREEN,'╞');
  Wbprintc(BRD_RGT,9,_MAGENTA|INTENSE|GREEN,'┤');
  Wprts(1,1,_CYAN|BLACK,"Вид");
  Wprts(1,5,_CYAN|BLACK,"модели");
  Wprts(3,1,_CYAN|BLACK,"Порядок");
  Wprts(3,9,_CYAN|BLACK,"модели");
  Wprts(4,1,_CYAN|BLACK,"Регуляризация");
  Wprts(6,1,_CYAN|BLACK,"Запаздывание");
  Wprts(7,1,_CYAN|BLACK,"Порядок");
  Wprts(7,9,_CYAN|BLACK,"тренда");
  Wprts(8,0,_CYAN|BLACK,"────────────────────────────");
  Wprts(9,1,_CYAN|BLACK,"░");
  Wprts(9,3,_CYAN|MAGENTA,"F3");
  Wprts(9,5,_CYAN|BROWN,":");
  Wprts(9,7,_CYAN|BLACK,"Выбор");
  Wprts(9,13,_CYAN|BLACK,"вида");
  Wprts(9,18,_CYAN|BLACK,"модели");
  Wprts(9,25,_CYAN|BLACK,"░");

  _har_model_2STR();
  EntPush();
  EntBuild(&_har_model_Frm);
  EntDsp();
  EntFree();
  EntPop();

  return;
}
LCL VOID CTYP _har_model_2STR(NOARG)
{
  strcpy(har_model_var2,wid_modeli); strsetsz(har_model_var2,15);
  cvtic(har_model_var5,p,2);
  cvtic(har_model_var6,qq,2);
  cvtic(har_model_var8,q,2);
  cvtic(har_model_var9,n1,2);
 return;
}
LCL VOID CTYP _har_model_2VAL(NOARG)
{
    strcpy(wid_modeli,har_model_var2);
    p=cvtci(har_model_var5);
    qq=cvtci(har_model_var6);
    q=cvtci(har_model_var8);
    n1=cvtci(har_model_var9);
 return;
}

LCL VOID CTYP _har_model_ENTRY(NOARG)
{
 IntT val;
 KbndP tcxl_old_kb,tcxl_kb=NULL;

 _har_model_OPEN();
 tcxl_old_kb=KbndChg(tcxl_kb);
 _har_model_2STR();
 EntPush();
 EntBuild(&_har_model_Frm);
 CurShow();
 EntResult=0;
 val=EntGet(_har_model_Fld[0].ftag);
 CurHide();
 EntPop();
 KbndChg(tcxl_old_kb);
 Wclose();
 if(val!=ERR_ARG)
    {
    _har_model_2VAL();
    EntResult=1;
    }
}

LCL VOID CTYP _opt8_ACT(NOARG)
{
poly_sin();
return;
}

LCL VOID CTYP _opt13_ACT(NOARG)
{
from_stend();
return;
}

LCL VOID CTYP _opt18_ACT(NOARG)
{
vi_et_tabl();
return;
}

LCL VOID CTYP _opt22_ACT(NOARG)
{
vi_et_graph();
return;
}

LCL IbldT _wid_et_s_Itm[]={
{"Полигармонический",'\0',ITM_NOR,1,2,  31,HLP_NONE,
   0,32,NULL,_opt8_ACT,NULL,
   "",NULL},
{"    Из файла     ",'\0',ITM_NOR,2,2,  33,HLP_NONE,
   0,34,NULL,_file_et_ENTRY,NULL,
   "",NULL},
{"    Со стенда    ",'\0',ITM_NOR,3,2,  35,HLP_NONE,
   0,36,NULL,_opt13_ACT,NULL,
   "",NULL},
{" В виде таблицы  ",'\0',ITM_NOR,5,2,  37,HLP_NONE,
   0,38,NULL,_opt18_ACT,NULL,
   "",NULL},
{" В виде графиков ",'\0',ITM_NOR,6,2,  39,HLP_NONE,
   0,40,NULL,_opt22_ACT,NULL,
   "",NULL},
{"     В файл      ",'\0',ITM_NOR,8,2,  41,HLP_NONE,
   0,42,NULL,_ifile_et_ENTRY,NULL,
   "",NULL},
};


LCL VOID CTYP _wid_et_s_MSG(NOARG);
LCL MbldT _wid_et_s_Mnu={
   _wid_et_s_Itm,6,4,49,15,71,  MNU_OMN|MNU_SAV|MNU_DSP|MNU_NQS,BOX_SNG,
   _LGREY|BROWN,_BLUE|INTENSE|LGREY,_BLUE|INTENSE|LGREY,
   _BLUE|BLACK,_BLUE|BLACK,_CYAN|BLACK,
   0,_wid_et_s_MSG,43, 10,0,0, 0xff,0xff,0xff};

LCL VOID CTYP _wid_et_s_MSG(NOARG)
{

 CurHide();
  Wprts(0,0,_BLUE|INTENSE|LGREY,"┌────\020" "");
  Wprts(0,7,_BLUE|INTENSE|LGREY,"Задание");
  Wprts(0,15,_BLUE|INTENSE|LGREY,"\021" "────┐");
  Wprts(1,0,_BLUE|INTENSE|LGREY,"│");
  Wprts(1,20,_BLUE|INTENSE|LGREY,"│");
  Wprts(2,0,_BLUE|INTENSE|LGREY,"│");
  Wprts(2,20,_BLUE|INTENSE|LGREY,"│");
  Wprts(3,0,_BLUE|INTENSE|LGREY,"│");
  Wprts(3,20,_BLUE|INTENSE|LGREY,"│");
  Wprts(4,0,_BLUE|INTENSE|LGREY,"├───\020" "");
  Wprts(4,6,_BLUE|INTENSE|LGREY,"Просмотр");
  Wprts(4,15,_BLUE|INTENSE|LGREY,"\021" "────┤");
  Wprts(5,0,_BLUE|INTENSE|LGREY,"│");
  Wprts(5,20,_BLUE|INTENSE|LGREY,"│");
  Wprts(6,0,_BLUE|INTENSE|LGREY,"│");
  Wprts(6,20,_BLUE|INTENSE|LGREY,"│");
  Wprts(7,0,_BLUE|INTENSE|LGREY,"├───\020" "");
  Wprts(7,7,_BLUE|INTENSE|BROWN,"Запись");
  Wprts(7,15,_BLUE|INTENSE|LGREY,"\021" "────┤");
  Wprts(8,0,_BLUE|INTENSE|LGREY,"│");
  Wprts(8,20,_BLUE|INTENSE|LGREY,"│");
  Wprts(9,0,_BLUE|INTENSE|LGREY,"└───────────────────┘");
  {
  MnuDsp(&_wid_et_s_Mnu);
  }
  return;
}
LCL VOID CTYP _wid_et_s_MENU(NOARG)
{
 KbndP tcxl_old_kb,tcxl_kb=NULL;

 MbldTag(&_wid_et_s_Mnu)=IbldTag(&_wid_et_s_Itm[0]);
 tcxl_old_kb=KbndChg(tcxl_kb);

 MnuBuild(&_wid_et_s_Mnu);
 MnuGet();
 KbndChg(tcxl_old_kb);
}

LCL VOID CTYP _opt9_ACT(NOARG)
{
Loop_debug();
return;
}

LCL VOID CTYP _opt12_ACT(NOARG)
{
Loop();
return;
}

LCL VOID CTYP _opt16_ACT(NOARG)
{
m_p_garm();
return;
}

LCL VOID CTYP _opt19_ACT(NOARG)
{
p_garm();
return;
}

LCL VOID CTYP _opt25_ACT(NOARG)
{
tabl_time();
return;
}

LCL VOID CTYP _opt27_ACT(NOARG)
{
graf_time();
return;
}

LCL VOID CTYP _opt28_ACT(NOARG)
{
graf_2time();
return;
}

LCL VOID CTYP _opt31_ACT(NOARG)
{
Razgruzka();
return;
}

LCL IbldT _wid_upr_Itm[]={
{"       Синхронное       ",'\0',ITM_NOR,1,2,  44,HLP_NONE,
   0,45,NULL,_opt9_ACT,NULL,
   "",NULL},
{"      Асинхронное       ",'\0',ITM_NOR,2,2,  46,HLP_NONE,
   0,47,NULL,_opt12_ACT,NULL,
   "",NULL},
{"       С моделью        ",'\0',ITM_NOR,4,2,  48,HLP_NONE,
   0,49,NULL,_opt16_ACT,NULL,
   "",NULL},
{"       Без модели       ",'\0',ITM_NOR,5,2,  50,HLP_NONE,
   0,51,NULL,_opt19_ACT,NULL,
   "",NULL},
{"    Просмотр таблицы    ",'9',ITM_NOR,8,2,  52,HLP_NONE,
   0,53,NULL,_opt25_ACT,NULL,
   "",NULL},
{"  Графики (вход/выход)  ",'2',ITM_NOR,9,2,  54,HLP_NONE,
   0,55,NULL,_opt27_ACT,NULL,
   "",NULL},
{" Графики (эталон/выход) ",'6',ITM_NOR,10,2,  56,HLP_NONE,
   0,57,NULL,_opt28_ACT,NULL,
   "",NULL},
{"     Запись в файл      ",'6',ITM_NOR,11,2,  58,HLP_NONE,
   0,59,NULL,_file_upr_ENTRY,NULL,
   "",NULL},
{"       Разгрузка        ",'\0',ITM_NOR,14,2,  60,HLP_NONE,
   0,61,NULL,_opt31_ACT,NULL,
   "",NULL},
};


LCL VOID CTYP _wid_upr_MSG(NOARG);
LCL MbldT _wid_upr_Mnu={
   _wid_upr_Itm,9,4,50,21,79,  MNU_OMN|MNU_SAV|MNU_DSP|MNU_NQS,BOX_SNG,
   _LGREY|BROWN,_BLUE|INTENSE|LGREY,_BLUE|INTENSE|LGREY,
   _BLUE|BLACK,_BLUE|BLACK,_CYAN|BLACK,
   0,_wid_upr_MSG,62, 10,0,0, 0xff,0xff,0xff};

LCL VOID CTYP _wid_upr_MSG(NOARG)
{

 CurHide();
  Wprts(0,1,_BLUE|INTENSE|BROWN,"┌");
  Wprts(0,2,_BLUE|INTENSE|LGREY,"─");
  Wprts(0,3,_BLUE|INTENSE|BROWN,"───\020" " Адаптивное \021" "──────┐");
  Wprts(1,1,_BLUE|INTENSE|BROWN,"│");
  Wprts(1,26,_BLUE|INTENSE|BROWN,"│");
  Wprts(2,1,_BLUE|INTENSE|BROWN,"│");
  Wprts(2,26,_BLUE|INTENSE|BROWN,"│");
  Wprts(3,1,_BLUE|INTENSE|BROWN,"├───\020" " Неадаптивное \021" "─────┤");
  Wprts(4,1,_BLUE|INTENSE|BROWN,"│");
  Wprts(4,26,_BLUE|INTENSE|BROWN,"│");
  Wprts(5,1,_BLUE|INTENSE|BROWN,"│");
  Wprts(5,26,_BLUE|INTENSE|BROWN,"│");
  Wprts(6,1,_BLUE|INTENSE|BROWN,"└────────────────────────┘");
  Wprts(7,1,_BLUE|INTENSE|BROWN,"┌────\020" " Результаты \021" "──────┐");
  Wprts(8,1,_BLUE|INTENSE|BROWN,"│");
  Wprts(8,26,_BLUE|INTENSE|BROWN,"│");
  Wprts(9,1,_BLUE|INTENSE|BROWN,"│");
  Wprts(9,26,_BLUE|INTENSE|BROWN,"│");
  Wprts(10,1,_BLUE|INTENSE|BROWN,"│");
  Wprts(10,26,_BLUE|INTENSE|BROWN,"│");
  Wprts(11,1,_BLUE|INTENSE|LGREY,"│");
  Wprts(11,26,_BLUE|INTENSE|LGREY,"│");
  Wprts(12,1,_BLUE|INTENSE|BROWN,"└────────────────────────┘");
  Wprts(13,1,_BLUE|INTENSE|BROWN,"┌──\020" " Технологическое \021" "");
  Wprts(13,23,_BLUE|INTENSE|LGREY,"─");
  Wprts(13,24,_BLUE|INTENSE|BROWN,"──┐");
  Wprts(14,1,_BLUE|INTENSE|BROWN,"│");
  Wprts(14,26,_BLUE|INTENSE|BROWN,"│");
  Wprts(15,1,_BLUE|INTENSE|BROWN,"└────────────────────────┘");
  {
  MnuDsp(&_wid_upr_Mnu);
  }
  return;
}
LCL VOID CTYP _wid_upr_MENU(NOARG)
{
 KbndP tcxl_old_kb,tcxl_kb=NULL;

 MbldTag(&_wid_upr_Mnu)=IbldTag(&_wid_upr_Itm[0]);
 tcxl_old_kb=KbndChg(tcxl_kb);

 MnuBuild(&_wid_upr_Mnu);
 MnuGet();
 KbndChg(tcxl_old_kb);
}
LCL VOID CTYP _razgruzka_EXEC(NOARG)
{
GotoNull();  
  return;
}

LCL IbldT _static_mn_Itm[]={
{"   Исходные данные   ",'\0',ITM_NOR,1,2,  63,HLP_NONE,
   0,64,NULL,_ish_d_static_ENTRY,NULL,
   "",NULL},
{"Снятие статич. хар-к ",'\0',ITM_NOR,3,2,  65,HLP_NONE,
   0,66,NULL,_stat_msg_SHOW,NULL,
   "",NULL},
{"  Просмотр таблицы   ",'\0',ITM_NOR,5,2,  67,HLP_NONE,
   0,68,NULL,_tabl_stat_EXEC,NULL,
   "",NULL},
{"  Просмотр графиков  ",'\0',ITM_NOR,6,2,  69,HLP_NONE,
   0,70,NULL,_grf_stat_EXEC,NULL,
   "",NULL},
{"    Запись в файл    ",'\0',ITM_NOR,8,2,  71,HLP_NONE,
   0,72,NULL,_file_st_ENTRY,NULL,
   "",NULL},
};


LCL VOID CTYP _static_mn_MSG(NOARG);
LCL MbldT _static_mn_Mnu={
   _static_mn_Itm,5,7,15,18,41,  MNU_PUL|MNU_SAV|MNU_DSP|MNU_NQS,BOX_SNG,
   _LGREY|BROWN,_BLUE|INTENSE|BROWN,_BLUE|INTENSE|BROWN,
   _BLUE|BLACK,_BLUE|BLACK,_CYAN|BLACK,
   0,_static_mn_MSG,73, 10,0,0, 0xff,0xff,0xff};

LCL VOID CTYP _static_mn_MSG(NOARG)
{

 CurHide();
  Wmessage("\020" " Снятие статич.хар-к \021" "",BRD_TOP,2,_LGREY|BROWN);
  Wprts(0,1,_BLUE|INTENSE|BROWN,"┌─────────────────────┐");
  Wprts(1,1,_BLUE|INTENSE|BROWN,"│");
  Wprts(1,23,_BLUE|INTENSE|BROWN,"│");
  Wprts(2,1,_BLUE|INTENSE|BROWN,"├─────────────────────┤");
  Wprts(3,1,_BLUE|INTENSE|BROWN,"│");
  Wprts(3,23,_BLUE|INTENSE|BROWN,"│");
  Wprts(4,1,_BLUE|INTENSE|BROWN,"├─────────────────────┤");
  Wprts(5,1,_BLUE|INTENSE|BROWN,"│");
  Wprts(5,23,_BLUE|INTENSE|BROWN,"│");
  Wprts(6,1,_BLUE|INTENSE|BROWN,"│");
  Wprts(6,23,_BLUE|INTENSE|BROWN,"│");
  Wprts(7,1,_BLUE|INTENSE|BROWN,"├─────────────────────┤");
  Wprts(8,1,_BLUE|INTENSE|BROWN,"│");
  Wprts(8,23,_BLUE|INTENSE|BROWN,"│");
  Wprts(9,1,_BLUE|INTENSE|BROWN,"└─────────────────────┘");
  {
  MnuDsp(&_static_mn_Mnu);
  }
  return;
}
LCL VOID CTYP _static_mn_MENU(NOARG)
{
 KbndP tcxl_old_kb,tcxl_kb=NULL;

 MbldTag(&_static_mn_Mnu)=IbldTag(&_static_mn_Itm[0]);
 tcxl_old_kb=KbndChg(tcxl_kb);

 MnuBuild(&_static_mn_Mnu);
 MnuGet();
 KbndChg(tcxl_old_kb);
}
LCL VOID CTYP _wz_stat_EXEC(NOARG)
{
wz_s();    
  return;
}
LCL VOID CTYP _do_achh_EXEC(NOARG)
{
do_achh();  
  return;
}

LCL ChrT file_et_var7[16];
LCL ChrT file_et_var12[6];
LCL ChrT file_et_var13[6];
LCL ChrT file_et_var15[6];
LCL ChrT file_et_var16[6];
LCL ChrT file_et_var17[6];
LCL ChrT file_et_var18[6];
LCL ChrT file_et_var19[6];
LCL ChrT file_et_var20[6];
LCL FbldT _file_et_Fld[]={
 {"",0,0, file_et_var7,1,12,
  "***************",NULL,NULL,NULL,
  0,74,HLP_NONE,
  FLD_NUL|FLD_TRM,0,FLD_CHG},
 {"",0,0, file_et_var12,6,7,
  "99.99",NULL,NULL,NULL,
  0,75,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, file_et_var13,6,17,
  "99.99",NULL,NULL,NULL,
  0,76,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, file_et_var15,7,7,
  "99.99",NULL,NULL,NULL,
  0,77,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, file_et_var16,7,17,
  "99.99",NULL,NULL,NULL,
  0,78,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, file_et_var17,8,7,
  "99.99",NULL,NULL,NULL,
  0,79,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, file_et_var18,8,17,
  "99.99",NULL,NULL,NULL,
  0,80,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, file_et_var19,9,7,
  "99.99",NULL,NULL,NULL,
  0,81,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, file_et_var20,9,17,
  "99.99",NULL,NULL,NULL,
  0,82,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
};

LCL EbldT _file_et_Frm={
 _file_et_Fld,9,NULL,NULL,83,0,
 0,_CYAN|BLACK,_BLUE|INTENSE|GREEN,_BLACK|DGREY
};
LCL VOID CTYP _file_et_OPEN(NOARG)
{

 Wopen(8,33,19,62,BOX_SNG,
       _MAGENTA|INTENSE|GREEN,_CYAN|BLACK);
 CurHide();
  Wmessage("\020" " Эталон из файла \021" "",BRD_TOP,6,_MAGENTA|INTENSE|GREEN);
  Wprts(1,1,_CYAN|BLACK,"Имя");
  Wprts(1,5,_CYAN|BLACK,"файла");
  Wprts(3,0,_CYAN|BLACK,"─────┬───────┬──────────────");
  Wprts(4,0,_CYAN|BLACK,"Канал│Статика│Коэффициент");
  Wprts(5,0,_CYAN|BLACK,"─────┼───────┼──────────────");
  Wprts(6,2,_CYAN|BLACK,"1");
  Wprts(6,5,_CYAN|BLACK,"│");
  Wprts(6,13,_CYAN|BLACK,"│");
  Wprts(7,2,_CYAN|BLACK,"2");
  Wprts(7,5,_CYAN|BLACK,"│");
  Wprts(7,13,_CYAN|BLACK,"│");
  Wprts(8,2,_CYAN|BLACK,"3");
  Wprts(8,5,_CYAN|BLACK,"│");
  Wprts(8,13,_CYAN|BLACK,"│");
  Wprts(9,2,_CYAN|BLACK,"4");
  Wprts(9,5,_CYAN|BLACK,"│");
  Wprts(9,13,_CYAN|BLACK,"│");

  _file_et_2STR();
  EntPush();
  EntBuild(&_file_et_Frm);
  EntDsp();
  EntFree();
  EntPop();

  _wybor_EXEC();
  return;
}
LCL VOID CTYP _file_et_2STR(NOARG)
{
  strcpy(file_et_var7,file_name); strsetsz(file_et_var7,15);
  cvtfc(file_et_var12,file_st[0],5,2);
  cvtfc(file_et_var13,file_k[0],5,2);
  cvtfc(file_et_var15,file_st[1],5,2);
  cvtfc(file_et_var16,file_k[1],5,2);
  cvtfc(file_et_var17,file_st[2],5,2);
  cvtfc(file_et_var18,file_k[2],5,2);
  cvtfc(file_et_var19,file_st[3],5,2);
  cvtfc(file_et_var20,file_k[3],5,2);
 return;
}
LCL VOID CTYP _file_et_2VAL(NOARG)
{
    strcpy(file_name,file_et_var7);
    file_st[0]=cvtcf(file_et_var12);
    file_k[0]=cvtcf(file_et_var13);
    file_st[1]=cvtcf(file_et_var15);
    file_k[1]=cvtcf(file_et_var16);
    file_st[2]=cvtcf(file_et_var17);
    file_k[2]=cvtcf(file_et_var18);
    file_st[3]=cvtcf(file_et_var19);
    file_k[3]=cvtcf(file_et_var20);
 return;
}

LCL VOID CTYP _file_et_ENTRY(NOARG)
{
 IntT val;
 KbndP tcxl_old_kb,tcxl_kb=NULL;

 _file_et_OPEN();
 tcxl_old_kb=KbndChg(tcxl_kb);
 _file_et_2STR();
 EntPush();
 EntBuild(&_file_et_Frm);
 CurShow();
 EntResult=0;
 val=EntGet(_file_et_Fld[0].ftag);
 CurHide();
 EntPop();
 KbndChg(tcxl_old_kb);
 Wclose();
 if(val!=ERR_ARG)
    {
    _file_et_2VAL();
    EntResult=1;
    }
}

LCL ChrT ifile_et_var10[16];
LCL ChrT ifile_et_var11[6];
LCL ChrT ifile_et_var14[6];
LCL FbldT _ifile_et_Fld[]={
 {"",0,0, ifile_et_var10,1,12,
  "***************",NULL,NULL,NULL,
  0,84,HLP_NONE,
  FLD_NUL|FLD_TRM,0,FLD_CHG},
 {"",0,0, ifile_et_var11,2,22,
  "99.99",NULL,NULL,NULL,
  0,85,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, ifile_et_var14,3,22,
  "99.99",NULL,NULL,NULL,
  0,86,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
};

LCL EbldT _ifile_et_Frm={
 _ifile_et_Fld,3,NULL,NULL,87,0,
 0,_CYAN|BLACK,_BLUE|INTENSE|GREEN,_BLACK|DGREY
};
LCL VOID CTYP _ifile_et_OPEN(NOARG)
{

 Wopen(11,46,17,75,BOX_SNG,
       _MAGENTA|INTENSE|GREEN,_CYAN|BLACK);
 CurHide();
  Wmessage("\020" "   Эталон в файл   \021" "",BRD_TOP,3,_MAGENTA|INTENSE|GREEN);
  Wprts(1,1,_CYAN|BLACK,"Имя");
  Wprts(1,5,_CYAN|BLACK,"файла");
  Wprts(2,1,_CYAN|BLACK,"Масштаб.коэффициент");
  Wprts(3,1,_CYAN|BLACK,"Статика");

  _ifile_et_2STR();
  EntPush();
  EntBuild(&_ifile_et_Frm);
  EntDsp();
  EntFree();
  EntPop();

  return;
}
LCL VOID CTYP _ifile_et_2STR(NOARG)
{
  strcpy(ifile_et_var10,ifile_name); strsetsz(ifile_et_var10,15);
  cvtfc(ifile_et_var11,ifile_k,5,2);
  cvtfc(ifile_et_var14,ifile_st,5,2);
 return;
}
LCL VOID CTYP _ifile_et_2VAL(NOARG)
{
    strcpy(ifile_name,ifile_et_var10);
    ifile_k=cvtcf(ifile_et_var11);
    ifile_st=cvtcf(ifile_et_var14);
 return;
}

LCL VOID CTYP _ifile_et_ENTRY(NOARG)
{
 IntT val;
 KbndP tcxl_old_kb,tcxl_kb=NULL;

 _ifile_et_OPEN();
 tcxl_old_kb=KbndChg(tcxl_kb);
 _ifile_et_2STR();
 EntPush();
 EntBuild(&_ifile_et_Frm);
 CurShow();
 EntResult=0;
 val=EntGet(_ifile_et_Fld[0].ftag);
 CurHide();
 EntPop();
 KbndChg(tcxl_old_kb);
 Wclose();
 if(val!=ERR_ARG)
    {
    _ifile_et_2VAL();
    EntResult=1;
    }
  _write_et_EXEC();
}

LCL ChrT file_upr_var21[16];
LCL FbldT _file_upr_Fld[]={
 {"",0,0, file_upr_var21,1,12,
  "***************",NULL,NULL,NULL,
  0,88,HLP_NONE,
  FLD_NUL|FLD_TRM,0,FLD_CHG},
};

LCL EbldT _file_upr_Frm={
 _file_upr_Fld,1,NULL,NULL,89,0,
 0,_CYAN|BLACK,_BLUE|INTENSE|GREEN,_BLACK|DGREY
};
LCL VOID CTYP _file_upr_OPEN(NOARG)
{

 Wopen(17,47,21,76,BOX_SNG,
       _MAGENTA|INTENSE|GREEN,_CYAN|BLACK);
 CurHide();
  Wmessage("\020" " Управление в файл \021" "",BRD_TOP,3,_MAGENTA|INTENSE|GREEN);
  Wprts(1,1,_CYAN|BLACK,"Имя");
  Wprts(1,5,_CYAN|BLACK,"файла");

  _file_upr_2STR();
  EntPush();
  EntBuild(&_file_upr_Frm);
  EntDsp();
  EntFree();
  EntPop();

  return;
}
LCL VOID CTYP _file_upr_2STR(NOARG)
{
  strcpy(file_upr_var21,ufile_name); strsetsz(file_upr_var21,15);
 return;
}
LCL VOID CTYP _file_upr_2VAL(NOARG)
{
    strcpy(ufile_name,file_upr_var21);
 return;
}

LCL VOID CTYP _file_upr_ENTRY(NOARG)
{
 IntT val;
 KbndP tcxl_old_kb,tcxl_kb=NULL;

 _file_upr_OPEN();
 tcxl_old_kb=KbndChg(tcxl_kb);
 _file_upr_2STR();
 EntPush();
 EntBuild(&_file_upr_Frm);
 CurShow();
 EntResult=0;
 val=EntGet(_file_upr_Fld[0].ftag);
 CurHide();
 EntPop();
 KbndChg(tcxl_old_kb);
 Wclose();
 if(val!=ERR_ARG)
    {
    _file_upr_2VAL();
    EntResult=1;
    }
  _write_upr_EXEC();
}
LCL float mxmin;
LCL float mxmax;

LCL ChrT ish_d_static_var1[4];
LCL ChrT ish_d_static_var3[6];
LCL ChrT ish_d_static_var4[6];
LCL FbldT _ish_d_static_Fld[]={
 {"",0,0, ish_d_static_var1,1,37,
  "999",NULL,NULL,NULL,
  0,90,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, ish_d_static_var3,2,37,
  "99.99",NULL,NULL,NULL,
  0,91,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, ish_d_static_var4,3,37,
  "99.99",NULL,NULL,NULL,
  0,92,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
};

LCL EbldT _ish_d_static_Frm={
 _ish_d_static_Fld,3,NULL,NULL,93,0,
 0,_CYAN|BLUE,_BLUE|INTENSE|GREEN,_BLACK|DGREY
};
LCL VOID CTYP _ish_d_static_OPEN(NOARG)
{

 Wopen(4,1,10,48,BOX_SNG,
       _MAGENTA|INTENSE|GREEN,_CYAN|BLUE);
 CurHide();
  Wmessage("\020" " Исх. данные для статических хар-к  \021" "",BRD_TOP,5,_MAGENTA|INTENSE|GREEN);
  Wprts(1,3,_CYAN|BLUE,"Число");
  Wprts(1,9,_CYAN|BLUE,"значений");
  Wprts(1,18,_CYAN|BLUE,"статических");
  Wprts(1,30,_CYAN|BLUE,"хар-к");
  Wprts(2,11,_CYAN|BLUE,"Нижняя");
  Wprts(2,18,_CYAN|BLUE,"граница");
  Wprts(2,26,_CYAN|BLUE,"диапазона");
  Wprts(3,10,_CYAN|BLUE,"Верхняя");
  Wprts(3,18,_CYAN|BLUE,"граница");
  Wprts(3,26,_CYAN|BLUE,"диапазона");

  _ish_d_static_2STR();
  EntPush();
  EntBuild(&_ish_d_static_Frm);
  EntDsp();
  EntFree();
  EntPop();

  return;
}
LCL VOID CTYP _ish_d_static_2STR(NOARG)
{
  cvtic(ish_d_static_var1,nq,3);
  cvtfc(ish_d_static_var3,mxmin,5,2);
  cvtfc(ish_d_static_var4,mxmax,5,2);
 return;
}
LCL VOID CTYP _ish_d_static_2VAL(NOARG)
{
    nq=cvtci(ish_d_static_var1);
    mxmin=cvtcf(ish_d_static_var3);
    mxmax=cvtcf(ish_d_static_var4);
 return;
}

LCL VOID CTYP _ish_d_static_ENTRY(NOARG)
{
 IntT val;
 KbndP tcxl_old_kb,tcxl_kb=NULL;

  _uw_EXEC();
 _ish_d_static_OPEN();
 tcxl_old_kb=KbndChg(tcxl_kb);
 _ish_d_static_2STR();
 EntPush();
 EntBuild(&_ish_d_static_Frm);
 CurShow();
 EntResult=0;
 val=EntGet(_ish_d_static_Fld[0].ftag);
 CurHide();
 EntPop();
 KbndChg(tcxl_old_kb);
 Wclose();
 if(val!=ERR_ARG)
    {
    _ish_d_static_2VAL();
    EntResult=1;
    }
  _um_EXEC();
}
LCL VOID CTYP _stat_msg_SHOW(NOARG)
{
 Wopen(5,22,14,60,BOX_DBL,
       _RED|INTENSE|BROWN,_RED|INTENSE|LGREY);
 Wshadow(_BLACK|DGREY);
 CurHide();
  Wprts(1,10,_RED|INTENSE|LGREY,"ИДЕТ");
  Wprts(1,15,_RED|INTENSE|LGREY,"ЭКСПЕРИМЕНТ");
  Wprts(3,1,_RED|INTENSE|LGREY,"по");
  Wprts(3,4,_RED|INTENSE|LGREY,"снятию");
  Wprts(3,11,_RED|INTENSE|LGREY,"статических");
  Wprts(3,23,_RED|INTENSE|LGREY,"характеристик");
  Wprts(4,4,_RED|INTENSE|LGREY,"прямых");
  Wprts(4,11,_RED|INTENSE|LGREY,"и");
  Wprts(4,13,_RED|INTENSE|LGREY,"перекрестных");
  Wprts(4,26,_RED|INTENSE|LGREY,"каналов");
  Wprts(5,9,_RED|INTENSE|LGREY,"исследуемой");
  Wprts(5,21,_RED|INTENSE|LGREY,"системы");
   {
 KbndP tcxl_old_kb,tcxl_kb=NULL;
 tcxl_old_kb=KbndChg(tcxl_kb);
  _do_stat_EXEC();
 KbndChg(tcxl_old_kb);
   }
 Wclose();
 return;
}
LCL VOID CTYP _tabl_stat_EXEC(NOARG)
{
tabl_stat();
  return;
}
LCL VOID CTYP _grf_stat_EXEC(NOARG)
{
graf4(xmin,xmax,ymin,ymax);
  return;
}

LCL ChrT file_st_var22[16];
LCL ChrT file_st_var23[6];
LCL ChrT file_st_var24[6];
LCL FbldT _file_st_Fld[]={
 {"",0,0, file_st_var22,1,12,
  "***************",NULL,NULL,NULL,
  0,94,HLP_NONE,
  FLD_NUL|FLD_TRM,0,FLD_CHG},
 {"",0,0, file_st_var23,2,22,
  "99.99",NULL,NULL,NULL,
  0,95,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, file_st_var24,3,22,
  "99.99",NULL,NULL,NULL,
  0,96,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
};

LCL EbldT _file_st_Frm={
 _file_st_Fld,3,NULL,NULL,97,0,
 0,_CYAN|BLACK,_BLUE|INTENSE|GREEN,_BLACK|DGREY
};
LCL VOID CTYP _file_st_OPEN(NOARG)
{

 Wopen(18,18,24,47,BOX_SNG,
       _MAGENTA|INTENSE|GREEN,_CYAN|BLACK);
 CurHide();
  Wmessage("\020" "Статич.хар-ки в файл \021" "",BRD_TOP,3,_MAGENTA|INTENSE|GREEN);
  Wprts(1,1,_CYAN|BLACK,"Имя");
  Wprts(1,5,_CYAN|BLACK,"файла");
  Wprts(2,1,_CYAN|BLACK,"Масштаб.коэффициент");
  Wprts(3,1,_CYAN|BLACK,"Статика");

  _file_st_2STR();
  EntPush();
  EntBuild(&_file_st_Frm);
  EntDsp();
  EntFree();
  EntPop();

  return;
}
LCL VOID CTYP _file_st_2STR(NOARG)
{
  strcpy(file_st_var22,sfile_name); strsetsz(file_st_var22,15);
  cvtfc(file_st_var23,sfile_k,5,2);
  cvtfc(file_st_var24,sfile_st,5,2);
 return;
}
LCL VOID CTYP _file_st_2VAL(NOARG)
{
    strcpy(sfile_name,file_st_var22);
    sfile_k=cvtcf(file_st_var23);
    sfile_st=cvtcf(file_st_var24);
 return;
}

LCL VOID CTYP _file_st_ENTRY(NOARG)
{
 IntT val;
 KbndP tcxl_old_kb,tcxl_kb=NULL;

 _file_st_OPEN();
 tcxl_old_kb=KbndChg(tcxl_kb);
 _file_st_2STR();
 EntPush();
 EntBuild(&_file_st_Frm);
 CurShow();
 EntResult=0;
 val=EntGet(_file_st_Fld[0].ftag);
 CurHide();
 EntPop();
 KbndChg(tcxl_old_kb);
 Wclose();
 if(val!=ERR_ARG)
    {
    _file_st_2VAL();
    EntResult=1;
    }
  _write_st_EXEC();
}
LCL VOID CTYP _wybor_EXEC(NOARG)
{
wybor=2;   
  return;
}
LCL VOID CTYP _write_et_EXEC(NOARG)
{
 if(EntResult)  write_et(); 
  return;
}
LCL VOID CTYP _write_upr_EXEC(NOARG)
{
if(EntResult) write_upr(); 
  return;
}
LCL VOID CTYP _uw_EXEC(NOARG)
{
mxmin=xmin*5.0;  
mxmax=xmax*5.0;  
  return;
}
LCL VOID CTYP _um_EXEC(NOARG)
{
xmin=mxmin/5.0;  
xmax=mxmax/5.0;  
  return;
}
LCL VOID CTYP _do_stat_EXEC(NOARG)
{
do_stat();  
  return;
}
LCL VOID CTYP _write_st_EXEC(NOARG)
{
 if(EntResult) write_st(); 
  return;
}


/*=====================================================================*/


int main(NOARG)
{
 LCL ChrT _RusUpl[0x100]="ЙйЦцУуКкЕеНнГгШшЩщЗзХхЪъФфЫыВвАаПп"
                         "РрОоЛлДдЖжЭэЯяЧчСсМмИиТтЬьБбЮюЁё";
   TcxlInit();
   TcxlKeyOff();
   NlsUpl=_RusUpl;
  _startup_EXEC();
 Wopen(0,0,24,79,BOX_SPA,
       _BLACK|LGREY,_BLACK|LGREY);
 CurHide();
   {
 KbndP tcxl_old_kb,tcxl_kb=NULL;
 tcxl_old_kb=KbndChg(tcxl_kb);
 KbndChg(tcxl_old_kb);
   }
{
 KbndP tcxl_old_kb,tcxl_kb=NULL;

 MbldTag(&_main_Mnu)=IbldTag(&_main_Itm[0]);
  _do_init_EXEC();
 tcxl_old_kb=KbndChg(tcxl_kb);

 MnuBuild(&_main_Mnu);
 MnuGet();
 KbndChg(tcxl_old_kb);
  _shutdown_EXEC();
}
   Wclose();
  return 0;
}

/*** END OF FILE ***/
