

/*
 *   Generated by  UI v2.00 
 *        February 7, 1995
 */


/* Module: INF_RAB.C ===================== */

#include <string.h>
#include <stdlib.h>

#include <tcxlcur.h>
#include <tcxlnls.h>
#include <tcxlwin.h>
#include <tcxlent.h>
#include <tcxlmnu.h>
#include <tcxlcod.h>
#include <tcxlinp.h>
#include <tcxlsel.h>
#include <tcxlstr.h>
#include <tcxlvid.h>
#include <tcxlhlp.h>

#define HLP_NONE 1


#ifndef __Struct_WDEF_
#define __Struct_WDEF_

       struct _WDEF
         {
         IntT BegC,BegR,EndC,EndR;   /* положение окна    */
         IntT MniC,MniR,MaxC,MaxR;   /* возможные размеры */
         BytT FrmT;                  /* тип бордюра       */
         AtrT FrmA;                  /* атрибуты бордюра  */
         AtrT Dat;                   /* атрибуты текста   */
         BytT Shadow;                /* тень              */
         AtrT Sat;                   /* цвет тени         */
         };
#endif

#ifdef __cplusplus
  extern "C" {
#endif
VOID CTYP MnuDsp(MbldP mnu);
KeyT CTYP EntSelect(NOARG);
GBL  IntT EntSelAct;
LCL  IntT EntResult;
#ifdef __cplusplus
   }
#endif

VOID CTYP _inf_main_2STR(NOARG);

VOID CTYP INF_RAB(NOARG)
{
 Wopen(6,25,11,49,BOX_SNG,
       _RED|INTENSE|BROWN,_RED|INTENSE|BROWN);
 CurHide();
  Wprts(0,4,_RED|INTENSE|BROWN,"Идет");
  Wprts(0,9,_RED|INTENSE|BROWN,"управление");
  Wprts(2,5,_RED|INTENSE|BROWN,"С");
  Wprts(2,7,_RED|INTENSE|BROWN,"Т");
  Wprts(2,9,_RED|INTENSE|BROWN,"Е");
  Wprts(2,11,_RED|INTENSE|BROWN,"Н");
  Wprts(2,13,_RED|INTENSE|BROWN,"Д");
  Wprts(2,15,_RED|INTENSE|BROWN,"О");
  Wprts(2,17,_RED|INTENSE|BROWN,"М");
  return;
}

/*** END OF FILE ***/
