

/*
 *   Generated by  UI v2.00 
 *        February 7, 1995
 */


/* Module: POLY_SIN.C ===================== */

#include <string.h>
#include <stdlib.h>

#include <tcxlcur.h>
#include <tcxlnls.h>
#include <tcxlwin.h>
#include <tcxlent.h>
#include <tcxlmnu.h>
#include <tcxlcod.h>
#include <tcxlinp.h>
#include <tcxlsel.h>
#include <tcxlstr.h>
#include <tcxlvid.h>
#include <tcxlhlp.h>

#define HLP_NONE 1


#ifndef __Struct_WDEF_
#define __Struct_WDEF_

       struct _WDEF
         {
         IntT BegC,BegR,EndC,EndR;   /* положение окна    */
         IntT MniC,MniR,MaxC,MaxR;   /* возможные размеры */
         BytT FrmT;                  /* тип бордюра       */
         AtrT FrmA;                  /* атрибуты бордюра  */
         AtrT Dat;                   /* атрибуты текста   */
         BytT Shadow;                /* тень              */
         AtrT Sat;                   /* цвет тени         */
         };
#endif

#ifdef __cplusplus
  extern "C" {
#endif
VOID CTYP MnuDsp(MbldP mnu);
KeyT CTYP EntSelect(NOARG);
GBL  IntT EntSelAct;
LCL  IntT EntResult;
#ifdef __cplusplus
   }
#endif
#include "pro_achh.h"

VOID CTYP _wybor_EXEC(NOARG);
VOID CTYP _main_param_2STR(NOARG);
VOID CTYP _main_param_OPEN(NOARG);


LCL ChrT main_param_var1[6];
LCL ChrT main_param_var2[6];
LCL ChrT main_param_var3[6];
LCL ChrT main_param_var4[6];
LCL ChrT main_param_var5[6];
LCL ChrT main_param_var6[6];
LCL ChrT main_param_var7[6];
LCL ChrT main_param_var8[6];
LCL ChrT main_param_var9[6];
LCL ChrT main_param_var10[6];
LCL ChrT main_param_var11[6];
LCL ChrT main_param_var12[6];
LCL ChrT main_param_var13[6];
LCL ChrT main_param_var14[6];
LCL ChrT main_param_var15[6];
LCL ChrT main_param_var16[6];
LCL ChrT main_param_var17[6];
LCL ChrT main_param_var18[6];
LCL ChrT main_param_var19[6];
LCL ChrT main_param_var20[6];
LCL ChrT main_param_var21[6];
LCL ChrT main_param_var22[6];
LCL ChrT main_param_var23[6];
LCL ChrT main_param_var24[6];
LCL ChrT main_param_var25[6];
LCL ChrT main_param_var26[6];
LCL ChrT main_param_var27[6];
LCL ChrT main_param_var28[6];
LCL ChrT main_param_var29[6];
LCL ChrT main_param_var30[6];
LCL ChrT main_param_var31[6];
LCL ChrT main_param_var32[6];
LCL ChrT main_param_var33[6];
LCL ChrT main_param_var34[6];
LCL ChrT main_param_var35[6];
LCL ChrT main_param_var36[6];
LCL ChrT main_param_var37[6];
LCL ChrT main_param_var38[6];
LCL ChrT main_param_var39[6];
LCL ChrT main_param_var40[6];
LCL FbldT _main_param_Fld[]={
 {"",0,0, main_param_var1,2,10,
  "99.99",NULL,NULL,NULL,
  0,1,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_param_var2,2,31,
  "99.99",NULL,NULL,NULL,
  0,2,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_param_var3,2,43,
  "99.99",NULL,NULL,NULL,
  0,3,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_param_var4,2,55,
  "99.99",NULL,NULL,NULL,
  0,4,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_param_var5,3,31,
  "99.99",NULL,NULL,NULL,
  0,5,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_param_var6,3,43,
  "99.99",NULL,NULL,NULL,
  0,6,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_param_var7,3,55,
  "99.99",NULL,NULL,NULL,
  0,7,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_param_var8,4,31,
  "99.99",NULL,NULL,NULL,
  0,8,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_param_var9,4,43,
  "99.99",NULL,NULL,NULL,
  0,9,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_param_var10,4,55,
  "99.99",NULL,NULL,NULL,
  0,10,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_param_var11,6,10,
  "99.99",NULL,NULL,NULL,
  0,11,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_param_var12,6,31,
  "99.99",NULL,NULL,NULL,
  0,12,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_param_var13,6,43,
  "99.99",NULL,NULL,NULL,
  0,13,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_param_var14,6,55,
  "99.99",NULL,NULL,NULL,
  0,14,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_param_var15,7,31,
  "99.99",NULL,NULL,NULL,
  0,15,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_param_var16,7,43,
  "99.99",NULL,NULL,NULL,
  0,16,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_param_var17,7,55,
  "99.99",NULL,NULL,NULL,
  0,17,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_param_var18,8,31,
  "99.99",NULL,NULL,NULL,
  0,18,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_param_var19,8,43,
  "99.99",NULL,NULL,NULL,
  0,19,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_param_var20,8,55,
  "99.99",NULL,NULL,NULL,
  0,20,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_param_var21,10,10,
  "99.99",NULL,NULL,NULL,
  0,21,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_param_var22,10,31,
  "99.99",NULL,NULL,NULL,
  0,22,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_param_var23,10,43,
  "99.99",NULL,NULL,NULL,
  0,23,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_param_var24,10,55,
  "99.99",NULL,NULL,NULL,
  0,24,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_param_var25,11,31,
  "99.99",NULL,NULL,NULL,
  0,25,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_param_var26,11,43,
  "99.99",NULL,NULL,NULL,
  0,26,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_param_var27,11,55,
  "99.99",NULL,NULL,NULL,
  0,27,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_param_var28,12,31,
  "99.99",NULL,NULL,NULL,
  0,28,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_param_var29,12,43,
  "99.99",NULL,NULL,NULL,
  0,29,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_param_var30,12,55,
  "99.99",NULL,NULL,NULL,
  0,30,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_param_var31,14,10,
  "99.99",NULL,NULL,NULL,
  0,31,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_param_var32,14,31,
  "99.99",NULL,NULL,NULL,
  0,32,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_param_var33,14,43,
  "99.99",NULL,NULL,NULL,
  0,33,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_param_var34,14,55,
  "99.99",NULL,NULL,NULL,
  0,34,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_param_var35,15,31,
  "99.99",NULL,NULL,NULL,
  0,35,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_param_var36,15,43,
  "99.99",NULL,NULL,NULL,
  0,36,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_param_var37,15,55,
  "99.99",NULL,NULL,NULL,
  0,37,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_param_var38,16,31,
  "99.99",NULL,NULL,NULL,
  0,38,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_param_var39,16,43,
  "99.99",NULL,NULL,NULL,
  0,39,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
 {"",0,0, main_param_var40,16,55,
  "99.99",NULL,NULL,NULL,
  0,40,HLP_NONE,
  FLD_NUL|FLD_DEC,0,FLD_CHG},
};

LCL EbldT _main_param_Frm={
 _main_param_Fld,40,NULL,NULL,41,0,
 0,_CYAN|BLACK,_LGREY|BLACK,_BLACK|DGREY
};
LCL VOID CTYP _main_param_OPEN(NOARG)
{

 Wopen(4,10,22,74,BOX_SNG,
       _MAGENTA|INTENSE|GREEN,_CYAN|BLACK);
 CurHide();
  Wbprintc(BRD_TOP,9,_MAGENTA|INTENSE|GREEN,'╥');
  Wbprintc(BRD_TOP,17,_MAGENTA|INTENSE|GREEN,'┬');
  Wbprintc(BRD_TOP,28,_MAGENTA|INTENSE|GREEN,'┬');
  Wbprintc(BRD_TOP,40,_MAGENTA|INTENSE|GREEN,'┬');
  Wbprintc(BRD_TOP,52,_MAGENTA|INTENSE|GREEN,'┬');
  Wbprintc(BRD_BOT,9,_MAGENTA|INTENSE|GREEN,'╨');
  Wbprintc(BRD_BOT,17,_MAGENTA|INTENSE|GREEN,'┴');
  Wbprintc(BRD_BOT,28,_MAGENTA|INTENSE|GREEN,'┴');
  Wbprintc(BRD_BOT,40,_MAGENTA|INTENSE|GREEN,'┴');
  Wbprintc(BRD_BOT,52,_MAGENTA|INTENSE|GREEN,'┴');
  Wbprintc(BRD_LFT,2,_MAGENTA|INTENSE|GREEN,'├');
  Wbprintc(BRD_LFT,6,_MAGENTA|INTENSE|GREEN,'├');
  Wbprintc(BRD_LFT,10,_MAGENTA|INTENSE|GREEN,'├');
  Wbprintc(BRD_LFT,14,_MAGENTA|INTENSE|GREEN,'├');
  Wbprintc(BRD_RGT,2,_MAGENTA|INTENSE|GREEN,'┤');
  Wbprintc(BRD_RGT,6,_MAGENTA|INTENSE|GREEN,'┤');
  Wbprintc(BRD_RGT,10,_MAGENTA|INTENSE|GREEN,'┤');
  Wbprintc(BRD_RGT,14,_MAGENTA|INTENSE|GREEN,'┤');
  Wprts(0,8,_CYAN|BLACK,"║Статика│");
  Wprts(0,18,_CYAN|BLACK,"Параметры│1");
  Wprts(0,30,_CYAN|BLACK,"гармоника│2");
  Wprts(0,42,_CYAN|BLACK,"гармоника│3");
  Wprts(0,54,_CYAN|BLACK,"гармоника");
  Wprts(1,0,_CYAN|BLACK,"────────╫───────┼──────────┼───────────┼───────────┼───────────");
  Wprts(2,8,_CYAN|BLACK,"║");
  Wprts(2,16,_CYAN|BLACK,"│");
  Wprts(2,18,_CYAN|BLACK,"Амплитуда│");
  Wprts(2,39,_CYAN|BLACK,"│");
  Wprts(2,51,_CYAN|BLACK,"│");
  Wprts(3,0,_CYAN|BLACK,"1");
  Wprts(3,2,_CYAN|BLACK,"Канал");
  Wprts(3,8,_CYAN|BLACK,"║");
  Wprts(3,16,_CYAN|BLACK,"│");
  Wprts(3,18,_CYAN|BLACK,"Частота");
  Wprts(3,27,_CYAN|BLACK,"│");
  Wprts(3,39,_CYAN|BLACK,"│");
  Wprts(3,51,_CYAN|BLACK,"│");
  Wprts(4,8,_CYAN|BLACK,"║");
  Wprts(4,16,_CYAN|BLACK,"│");
  Wprts(4,18,_CYAN|BLACK,"Фаза");
  Wprts(4,27,_CYAN|BLACK,"│");
  Wprts(4,39,_CYAN|BLACK,"│");
  Wprts(4,51,_CYAN|BLACK,"│");
  Wprts(5,0,_CYAN|BLACK,"────────╫───────┼──────────┼───────────┼───────────┼───────────");
  Wprts(6,8,_CYAN|BLACK,"║");
  Wprts(6,16,_CYAN|BLACK,"│");
  Wprts(6,18,_CYAN|BLACK,"Амплитуда│");
  Wprts(6,39,_CYAN|BLACK,"│");
  Wprts(6,51,_CYAN|BLACK,"│");
  Wprts(7,0,_CYAN|BLACK,"2");
  Wprts(7,2,_CYAN|BLACK,"Канал");
  Wprts(7,8,_CYAN|BLACK,"║");
  Wprts(7,16,_CYAN|BLACK,"│");
  Wprts(7,18,_CYAN|BLACK,"Частота");
  Wprts(7,27,_CYAN|BLACK,"│");
  Wprts(7,39,_CYAN|BLACK,"│");
  Wprts(7,51,_CYAN|BLACK,"│");
  Wprts(8,8,_CYAN|BLACK,"║");
  Wprts(8,16,_CYAN|BLACK,"│");
  Wprts(8,18,_CYAN|BLACK,"Фаза");
  Wprts(8,27,_CYAN|BLACK,"│");
  Wprts(8,39,_CYAN|BLACK,"│");
  Wprts(8,51,_CYAN|BLACK,"│");
  Wprts(9,0,_CYAN|BLACK,"────────╫───────┼──────────┼───────────┼───────────┼───────────");
  Wprts(10,8,_CYAN|BLACK,"║");
  Wprts(10,16,_CYAN|BLACK,"│");
  Wprts(10,18,_CYAN|BLACK,"Амплитуда│");
  Wprts(10,39,_CYAN|BLACK,"│");
  Wprts(10,51,_CYAN|BLACK,"│");
  Wprts(11,0,_CYAN|BLACK,"3");
  Wprts(11,2,_CYAN|BLACK,"Канал");
  Wprts(11,8,_CYAN|BLACK,"║");
  Wprts(11,16,_CYAN|BLACK,"│");
  Wprts(11,18,_CYAN|BLACK,"Частота");
  Wprts(11,27,_CYAN|BLACK,"│");
  Wprts(11,39,_CYAN|BLACK,"│");
  Wprts(11,51,_CYAN|BLACK,"│");
  Wprts(12,8,_CYAN|BLACK,"║");
  Wprts(12,16,_CYAN|BLACK,"│");
  Wprts(12,18,_CYAN|BLACK,"Фаза");
  Wprts(12,27,_CYAN|BLACK,"│");
  Wprts(12,39,_CYAN|BLACK,"│");
  Wprts(12,51,_CYAN|BLACK,"│");
  Wprts(13,0,_CYAN|BLACK,"────────╫───────┼──────────┼───────────┼───────────┼───────────");
  Wprts(14,8,_CYAN|BLACK,"║");
  Wprts(14,16,_CYAN|BLACK,"│");
  Wprts(14,18,_CYAN|BLACK,"Амплитуда│");
  Wprts(14,39,_CYAN|BLACK,"│");
  Wprts(14,51,_CYAN|BLACK,"│");
  Wprts(15,0,_CYAN|BLACK,"4");
  Wprts(15,2,_CYAN|BLACK,"Канал");
  Wprts(15,8,_CYAN|BLACK,"║");
  Wprts(15,16,_CYAN|BLACK,"│");
  Wprts(15,18,_CYAN|BLACK,"Частота");
  Wprts(15,27,_CYAN|BLACK,"│");
  Wprts(15,39,_CYAN|BLACK,"│");
  Wprts(15,51,_CYAN|BLACK,"│");
  Wprts(16,8,_CYAN|BLACK,"║");
  Wprts(16,16,_CYAN|BLACK,"│");
  Wprts(16,18,_CYAN|BLACK,"Фаза");
  Wprts(16,27,_CYAN|BLACK,"│");
  Wprts(16,39,_CYAN|BLACK,"│");
  Wprts(16,51,_CYAN|BLACK,"│");

  _main_param_2STR();
  EntPush();
  EntBuild(&_main_param_Frm);
  EntDsp();
  EntFree();
  EntPop();

  _wybor_EXEC();
  return;
}
LCL VOID CTYP _main_param_2STR(NOARG)
{
  cvtfc(main_param_var1,u0[0],5,2);
  cvtfc(main_param_var2,a1[0],5,2);
  cvtfc(main_param_var3,a2[0],5,2);
  cvtfc(main_param_var4,a3[0],5,2);
  cvtfc(main_param_var5,f1[0],5,2);
  cvtfc(main_param_var6,f2[0],5,2);
  cvtfc(main_param_var7,f3[0],5,2);
  cvtfc(main_param_var8,fa1[0],5,2);
  cvtfc(main_param_var9,fa2[0],5,2);
  cvtfc(main_param_var10,fa3[0],5,2);
  cvtfc(main_param_var11,u0[1],5,2);
  cvtfc(main_param_var12,a1[1],5,2);
  cvtfc(main_param_var13,a2[1],5,2);
  cvtfc(main_param_var14,a3[1],5,2);
  cvtfc(main_param_var15,f1[1],5,2);
  cvtfc(main_param_var16,f2[1],5,2);
  cvtfc(main_param_var17,f3[1],5,2);
  cvtfc(main_param_var18,fa1[1],5,2);
  cvtfc(main_param_var19,fa2[1],5,2);
  cvtfc(main_param_var20,fa3[1],5,2);
  cvtfc(main_param_var21,u0[2],5,2);
  cvtfc(main_param_var22,a1[2],5,2);
  cvtfc(main_param_var23,a2[2],5,2);
  cvtfc(main_param_var24,a3[2],5,2);
  cvtfc(main_param_var25,f1[2],5,2);
  cvtfc(main_param_var26,f2[2],5,2);
  cvtfc(main_param_var27,f3[2],5,2);
  cvtfc(main_param_var28,fa1[2],5,2);
  cvtfc(main_param_var29,fa2[2],5,2);
  cvtfc(main_param_var30,fa3[2],5,2);
  cvtfc(main_param_var31,u0[3],5,2);
  cvtfc(main_param_var32,a1[3],5,2);
  cvtfc(main_param_var33,a2[3],5,2);
  cvtfc(main_param_var34,a3[3],5,2);
  cvtfc(main_param_var35,f1[3],5,2);
  cvtfc(main_param_var36,f2[3],5,2);
  cvtfc(main_param_var37,f3[3],5,2);
  cvtfc(main_param_var38,fa1[3],5,2);
  cvtfc(main_param_var39,fa2[3],5,2);
  cvtfc(main_param_var40,fa3[3],5,2);
 return;
}
LCL VOID CTYP _main_param_2VAL(NOARG)
{
    u0[0]=cvtcf(main_param_var1);
    a1[0]=cvtcf(main_param_var2);
    a2[0]=cvtcf(main_param_var3);
    a3[0]=cvtcf(main_param_var4);
    f1[0]=cvtcf(main_param_var5);
    f2[0]=cvtcf(main_param_var6);
    f3[0]=cvtcf(main_param_var7);
    fa1[0]=cvtcf(main_param_var8);
    fa2[0]=cvtcf(main_param_var9);
    fa3[0]=cvtcf(main_param_var10);
    u0[1]=cvtcf(main_param_var11);
    a1[1]=cvtcf(main_param_var12);
    a2[1]=cvtcf(main_param_var13);
    a3[1]=cvtcf(main_param_var14);
    f1[1]=cvtcf(main_param_var15);
    f2[1]=cvtcf(main_param_var16);
    f3[1]=cvtcf(main_param_var17);
    fa1[1]=cvtcf(main_param_var18);
    fa2[1]=cvtcf(main_param_var19);
    fa3[1]=cvtcf(main_param_var20);
    u0[2]=cvtcf(main_param_var21);
    a1[2]=cvtcf(main_param_var22);
    a2[2]=cvtcf(main_param_var23);
    a3[2]=cvtcf(main_param_var24);
    f1[2]=cvtcf(main_param_var25);
    f2[2]=cvtcf(main_param_var26);
    f3[2]=cvtcf(main_param_var27);
    fa1[2]=cvtcf(main_param_var28);
    fa2[2]=cvtcf(main_param_var29);
    fa3[2]=cvtcf(main_param_var30);
    u0[3]=cvtcf(main_param_var31);
    a1[3]=cvtcf(main_param_var32);
    a2[3]=cvtcf(main_param_var33);
    a3[3]=cvtcf(main_param_var34);
    f1[3]=cvtcf(main_param_var35);
    f2[3]=cvtcf(main_param_var36);
    f3[3]=cvtcf(main_param_var37);
    fa1[3]=cvtcf(main_param_var38);
    fa2[3]=cvtcf(main_param_var39);
    fa3[3]=cvtcf(main_param_var40);
 return;
}

LCL VOID CTYP _wybor_EXEC(NOARG)
{
wybor=1; 
  return;
}
VOID CTYP POLY_SIN(NOARG)
{
{
 IntT val;
 KbndP tcxl_old_kb,tcxl_kb=NULL;

 _main_param_OPEN();
 tcxl_old_kb=KbndChg(tcxl_kb);
 _main_param_2STR();
 EntPush();
 EntBuild(&_main_param_Frm);
 CurShow();
 EntResult=0;
 val=EntGet(_main_param_Fld[0].ftag);
 CurHide();
 EntPop();
 KbndChg(tcxl_old_kb);
 Wclose();
 if(val!=ERR_ARG)
    {
    _main_param_2VAL();
    EntResult=1;
    }
}
  return;
}

/*** END OF FILE ***/
