

/*
 *   Generated by  UI v2.00 
 *        February 20, 1995
 */


/* Module: SYS_WZST.C ===================== */

#include <string.h>
#include <stdlib.h>

#include <tcxlcur.h>
#include <tcxlnls.h>
#include <tcxlwin.h>
#include <tcxlent.h>
#include <tcxlmnu.h>
#include <tcxlcod.h>
#include <tcxlinp.h>
#include <tcxlsel.h>
#include <tcxlstr.h>
#include <tcxlvid.h>
#include <tcxlhlp.h>

#define HLP_NONE 1


#ifndef __Struct_WDEF_
#define __Struct_WDEF_

       struct _WDEF
         {
         IntT BegC,BegR,EndC,EndR;   /* положение окна    */
         IntT MniC,MniR,MaxC,MaxR;   /* возможные размеры */
         BytT FrmT;                  /* тип бордюра       */
         AtrT FrmA;                  /* атрибуты бордюра  */
         AtrT Dat;                   /* атрибуты текста   */
         BytT Shadow;                /* тень              */
         AtrT Sat;                   /* цвет тени         */
         };
#endif

#ifdef __cplusplus
  extern "C" {
#endif
VOID CTYP MnuDsp(MbldP mnu);
KeyT CTYP EntSelect(NOARG);
GBL  IntT EntSelAct;
LCL  IntT EntResult;
#ifdef __cplusplus
   }
#endif

VOID CTYP _wz_stat_msg_SHOW(NOARG);
VOID CTYP _tab_y_wz_EXEC(NOARG);
VOID CTYP _tab_beta_EXEC(NOARG);
VOID CTYP _wz_stat_EXEC(NOARG);
VOID CTYP _main_2STR(NOARG);
VOID CTYP _main_MSG(NOARG);
VOID CTYP _wz_stat_msg_2STR(NOARG);


LCL IbldT _main_Itm[]={
{" Запуск эксперимента ",'\0',ITM_NOR,1,2,  1,HLP_NONE,
   0,2,NULL,_wz_stat_msg_SHOW,NULL,
   "",NULL},
{"Просмотр выходн.сигн.",'\0',ITM_NOR,3,2,  3,HLP_NONE,
   0,4,NULL,_tab_y_wz_EXEC,NULL,
   "",NULL},
{"Просмотр коэфф.взаим.",'\0',ITM_NOR,4,2,  5,HLP_NONE,
   0,6,NULL,_tab_beta_EXEC,NULL,
   "",NULL},
{"Запись коэффиц.в файл",'\0',ITM_NOR,6,2,  7,HLP_NONE,
   0,8,NULL,NULL,NULL,
   "",NULL},
};


LCL VOID CTYP _main_MSG(NOARG);
LCL MbldT _main_Mnu={
   _main_Itm,4,4,27,13,53,  MNU_OMN|MNU_SAV|MNU_DSP|MNU_NQS,BOX_SNG,
   _LGREY|BROWN,_BLUE|INTENSE|BROWN,_BLUE|INTENSE|BROWN,
   _BLUE|BLACK,_BLUE|BLACK,_CYAN|BLACK,
   0,_main_MSG,9, 10,0,0, 0xff,0xff,0xff};

LCL VOID CTYP _main_MSG(NOARG)
{

 CurHide();
  Wmessage("\020" "Взаимовлиян.в статике\021" "",BRD_TOP,2,_LGREY|BROWN);
  Wprts(0,1,_BLUE|INTENSE|BROWN,"┌──────────────────────┐");
  Wprts(1,1,_BLUE|INTENSE|BROWN,"│");
  Wprts(1,24,_BLUE|INTENSE|BROWN,"│");
  Wprts(2,1,_BLUE|INTENSE|BROWN,"├──────────────────────┤");
  Wprts(3,1,_BLUE|INTENSE|BROWN,"│");
  Wprts(3,24,_BLUE|INTENSE|BROWN,"│");
  Wprts(4,1,_BLUE|INTENSE|BROWN,"│");
  Wprts(4,24,_BLUE|INTENSE|BROWN,"│");
  Wprts(5,1,_BLUE|INTENSE|BROWN,"├──────────────────────┤");
  Wprts(6,1,_BLUE|INTENSE|BROWN,"│");
  Wprts(6,24,_BLUE|INTENSE|BROWN,"│");
  Wprts(7,1,_BLUE|INTENSE|BROWN,"└──────────────────────┘");
  {
  MnuDsp(&_main_Mnu);
  }
  return;
}
LCL VOID CTYP _wz_stat_msg_SHOW(NOARG)
{
 Wopen(6,24,14,55,BOX_DBL,
       _RED|INTENSE|BROWN,_RED|INTENSE|LGREY);
 Wshadow(_BLACK|DGREY);
 CurHide();
  Wprts(1,7,_RED|INTENSE|LGREY,"ИДЕТ");
  Wprts(1,12,_RED|INTENSE|LGREY,"ЭКСПЕРИМЕНТ");
  Wprts(3,1,_RED|INTENSE|LGREY,"по");
  Wprts(3,4,_RED|INTENSE|LGREY,"исследованию");
  Wprts(3,17,_RED|INTENSE|LGREY,"взаимовлияния");
  Wprts(4,3,_RED|INTENSE|LGREY,"между");
  Wprts(4,9,_RED|INTENSE|LGREY,"каналами");
  Wprts(4,18,_RED|INTENSE|LGREY,"с");
  Wprts(4,20,_RED|INTENSE|LGREY,"СТАТИКЕ");
   {
 KbndP tcxl_old_kb,tcxl_kb=NULL;
 tcxl_old_kb=KbndChg(tcxl_kb);
  _wz_stat_EXEC();
 KbndChg(tcxl_old_kb);
   }
 Wclose();
 return;
}
LCL VOID CTYP _tab_y_wz_EXEC(NOARG)
{
tab_y_wz(); 
  return;
}
LCL VOID CTYP _tab_beta_EXEC(NOARG)
{
tab_beta(); 
  return;
}
LCL VOID CTYP _wz_stat_EXEC(NOARG)
{
wz_stat();  
  return;
}
VOID CTYP SYS_WZST(NOARG)
{
{
 KbndP tcxl_old_kb,tcxl_kb=NULL;

 MbldTag(&_main_Mnu)=IbldTag(&_main_Itm[0]);
 tcxl_old_kb=KbndChg(tcxl_kb);

 MnuBuild(&_main_Mnu);
 MnuGet();
 KbndChg(tcxl_old_kb);
}
  return;
}

/*** END OF FILE ***/
